# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 452a57f98aea89771abe68a2afb73a015a8948a0487a8b4f7d4d55ba47a9c5b801eb1915a8511f3c6992df72b0c02f02e4f2d83010892458d6ed13d31a917ddf

test:
  secret_key_base: e93b772df09cff8b20c1ff2c97ee91f34cdeb40893d30d2edabe3141aacb7f69f41a5b8b787973fb1cff301912fe01914810267f3e121887cceef156b1bbd273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
